// Code generated by mlflow/go/cmd/generate/main.go. DO NOT EDIT.

package main

import "C"
import (
	"unsafe"
	"github.com/mlflow/mlflow-go-backend/pkg/protos"
)
//export ModelRegistryServiceCreateRegisteredModel
func ModelRegistryServiceCreateRegisteredModel(serviceID int64, requestData unsafe.Pointer, requestSize C.int, responseSize *C.int) unsafe.Pointer {
	service, err := modelRegistryServices.Get(serviceID)
	if err != nil {
		return makePointerFromError(err, responseSize)
	}
	return invokeServiceMethod(service.CreateRegisteredModel, new(protos.CreateRegisteredModel), requestData, requestSize, responseSize)
}
//export ModelRegistryServiceRenameRegisteredModel
func ModelRegistryServiceRenameRegisteredModel(serviceID int64, requestData unsafe.Pointer, requestSize C.int, responseSize *C.int) unsafe.Pointer {
	service, err := modelRegistryServices.Get(serviceID)
	if err != nil {
		return makePointerFromError(err, responseSize)
	}
	return invokeServiceMethod(service.RenameRegisteredModel, new(protos.RenameRegisteredModel), requestData, requestSize, responseSize)
}
//export ModelRegistryServiceUpdateRegisteredModel
func ModelRegistryServiceUpdateRegisteredModel(serviceID int64, requestData unsafe.Pointer, requestSize C.int, responseSize *C.int) unsafe.Pointer {
	service, err := modelRegistryServices.Get(serviceID)
	if err != nil {
		return makePointerFromError(err, responseSize)
	}
	return invokeServiceMethod(service.UpdateRegisteredModel, new(protos.UpdateRegisteredModel), requestData, requestSize, responseSize)
}
//export ModelRegistryServiceDeleteRegisteredModel
func ModelRegistryServiceDeleteRegisteredModel(serviceID int64, requestData unsafe.Pointer, requestSize C.int, responseSize *C.int) unsafe.Pointer {
	service, err := modelRegistryServices.Get(serviceID)
	if err != nil {
		return makePointerFromError(err, responseSize)
	}
	return invokeServiceMethod(service.DeleteRegisteredModel, new(protos.DeleteRegisteredModel), requestData, requestSize, responseSize)
}
//export ModelRegistryServiceGetRegisteredModel
func ModelRegistryServiceGetRegisteredModel(serviceID int64, requestData unsafe.Pointer, requestSize C.int, responseSize *C.int) unsafe.Pointer {
	service, err := modelRegistryServices.Get(serviceID)
	if err != nil {
		return makePointerFromError(err, responseSize)
	}
	return invokeServiceMethod(service.GetRegisteredModel, new(protos.GetRegisteredModel), requestData, requestSize, responseSize)
}
//export ModelRegistryServiceGetLatestVersions
func ModelRegistryServiceGetLatestVersions(serviceID int64, requestData unsafe.Pointer, requestSize C.int, responseSize *C.int) unsafe.Pointer {
	service, err := modelRegistryServices.Get(serviceID)
	if err != nil {
		return makePointerFromError(err, responseSize)
	}
	return invokeServiceMethod(service.GetLatestVersions, new(protos.GetLatestVersions), requestData, requestSize, responseSize)
}
//export ModelRegistryServiceUpdateModelVersion
func ModelRegistryServiceUpdateModelVersion(serviceID int64, requestData unsafe.Pointer, requestSize C.int, responseSize *C.int) unsafe.Pointer {
	service, err := modelRegistryServices.Get(serviceID)
	if err != nil {
		return makePointerFromError(err, responseSize)
	}
	return invokeServiceMethod(service.UpdateModelVersion, new(protos.UpdateModelVersion), requestData, requestSize, responseSize)
}
//export ModelRegistryServiceTransitionModelVersionStage
func ModelRegistryServiceTransitionModelVersionStage(serviceID int64, requestData unsafe.Pointer, requestSize C.int, responseSize *C.int) unsafe.Pointer {
	service, err := modelRegistryServices.Get(serviceID)
	if err != nil {
		return makePointerFromError(err, responseSize)
	}
	return invokeServiceMethod(service.TransitionModelVersionStage, new(protos.TransitionModelVersionStage), requestData, requestSize, responseSize)
}
//export ModelRegistryServiceDeleteModelVersion
func ModelRegistryServiceDeleteModelVersion(serviceID int64, requestData unsafe.Pointer, requestSize C.int, responseSize *C.int) unsafe.Pointer {
	service, err := modelRegistryServices.Get(serviceID)
	if err != nil {
		return makePointerFromError(err, responseSize)
	}
	return invokeServiceMethod(service.DeleteModelVersion, new(protos.DeleteModelVersion), requestData, requestSize, responseSize)
}
//export ModelRegistryServiceGetModelVersion
func ModelRegistryServiceGetModelVersion(serviceID int64, requestData unsafe.Pointer, requestSize C.int, responseSize *C.int) unsafe.Pointer {
	service, err := modelRegistryServices.Get(serviceID)
	if err != nil {
		return makePointerFromError(err, responseSize)
	}
	return invokeServiceMethod(service.GetModelVersion, new(protos.GetModelVersion), requestData, requestSize, responseSize)
}
//export ModelRegistryServiceSetRegisteredModelTag
func ModelRegistryServiceSetRegisteredModelTag(serviceID int64, requestData unsafe.Pointer, requestSize C.int, responseSize *C.int) unsafe.Pointer {
	service, err := modelRegistryServices.Get(serviceID)
	if err != nil {
		return makePointerFromError(err, responseSize)
	}
	return invokeServiceMethod(service.SetRegisteredModelTag, new(protos.SetRegisteredModelTag), requestData, requestSize, responseSize)
}
//export ModelRegistryServiceDeleteRegisteredModelTag
func ModelRegistryServiceDeleteRegisteredModelTag(serviceID int64, requestData unsafe.Pointer, requestSize C.int, responseSize *C.int) unsafe.Pointer {
	service, err := modelRegistryServices.Get(serviceID)
	if err != nil {
		return makePointerFromError(err, responseSize)
	}
	return invokeServiceMethod(service.DeleteRegisteredModelTag, new(protos.DeleteRegisteredModelTag), requestData, requestSize, responseSize)
}
//export ModelRegistryServiceSetRegisteredModelAlias
func ModelRegistryServiceSetRegisteredModelAlias(serviceID int64, requestData unsafe.Pointer, requestSize C.int, responseSize *C.int) unsafe.Pointer {
	service, err := modelRegistryServices.Get(serviceID)
	if err != nil {
		return makePointerFromError(err, responseSize)
	}
	return invokeServiceMethod(service.SetRegisteredModelAlias, new(protos.SetRegisteredModelAlias), requestData, requestSize, responseSize)
}
